[package]
name = "highlights"
version = "0.1.0"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
repository = "https://github.com/ThatsNoMoon/highlights"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "blocking", "time"] }
rusqlite = { version = "0.23", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.16"
once_cell = "1.4"
regex = "1.3"
log = "0.4"
env_logger = "0.7"
dotenv = "0.15"
prometheus = "0.9"
hyper = "0.13"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "current"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "collector",
    "gateway",
    "http",
    "model",
    "rustls_backend",
]
