[package]
name = "highlights"
version = "0.1.0"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
edition = "2018"

[dependencies]
automate = "0.3"
tokio = { version = "0.2", features = ["macros"] }
once_cell = "1.4"
futures = "0.3.0"
smallvec = "1.4"

[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "sqlite", "macros"]

[build-dependencies]
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "sqlite", "macros"]
