[package]
name = "highlights"
version = "0.1.0"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "blocking"] }
rusqlite = { version = "0.23", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.16"
once_cell = "1.4"
log = "0.4"
env_logger = "0.7"
dotenv = "0.15"

[dependencies.serenity]
version = "0.9.0-rc.0"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "rustls_backend",
]
