[package]
name = "highlights"
version = "1.0.0-beta.8"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
repository = "https://github.com/ThatsNoMoon/highlights"
license = "OSL-3.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "blocking", "time", "fs"] }
rusqlite = { version = "0.23", features = ["bundled", "backup"] }
r2d2 = "0.8"
r2d2_sqlite = "0.16"
once_cell = "1.4"
regex = "1.3"
chrono = "0.4"
indoc = "1.0"
log = { version = "0.4", features = ["std"] }
env_logger = "0.7"
dotenv = "0.15"
prometheus = "0.9"
hyper = "0.13"
serde = { version = "1", features = ["derive"] }

[dependencies.serenity]
version = "0.9"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "collector",
    "gateway",
    "http",
    "model",
    "rustls_backend",
]

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["blocking", "rustls-tls"]
