[package]
name = "highlights"
version = "0.1.0"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
edition = "2018"

[dependencies]
automate = "0.3"
tokio = { version = "0.2", features = ["macros", "blocking"] }
once_cell = "1.4"
futures = "0.3.0"
smallvec = "1.4"
rusqlite = { version = "0.23", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.16"
